# Exploratory analysis of the mortality cohort.
#
# Rule for this file: no bare point estimates. Every comparison reports an
# effect size with a confidence interval and a p-value, and the p-values are
# Holm-adjusted because fifteen tests are run against one outcome.
#
# Writes docs/eda.md and docs/figs/*.png. Base graphics only -- no ggplot2, so
# the plots are one fewer dependency to install and to justify.

suppressPackageStartupMessages({
  library(survival)
  library(boot)
})

set.seed(20260823)

ANALYTIC  <- file.path("data", "analytic.csv")
DOCS_DIR  <- "docs"
FIGS_DIR  <- file.path(DOCS_DIR, "figs")
OUT_MD    <- file.path(DOCS_DIR, "eda.md")
BOOT_REPS <- 2000

if (!file.exists(ANALYTIC)) {
  stop("data/analytic.csv not found. Run `make features` first.", call. = FALSE)
}
dir.create(FIGS_DIR, recursive = TRUE, showWarnings = FALSE)

df <- read.csv(ANALYTIC, stringsAsFactors = FALSE)

CATEGORICAL <- c("sex", "race_eth", "education", "smoker",
                 "diabetes", "prior_chd", "prior_cancer")
CONTINUOUS  <- c("age", "income_ratio", "bmi", "waist",
                 "sbp", "dbp", "hdl", "hba1c")

# ------------------------------------------------------------- md helpers

con_md <- file(OUT_MD, open = "wt")
emit <- function(...) cat(..., "\n", sep = "", file = con_md)

fmt_p <- function(p) {
  ifelse(is.na(p), "n/a",
         ifelse(p < 1e-4, sprintf("%.2e", p), sprintf("%.4f", p)))
}

md_table <- function(dat, align = NULL) {
  cols <- names(dat)
  if (is.null(align)) align <- rep("---", length(cols))
  emit("| ", paste(cols, collapse = " | "), " |")
  emit("| ", paste(align, collapse = " | "), " |")
  for (i in seq_len(nrow(dat))) {
    emit("| ", paste(as.character(unlist(dat[i, ])), collapse = " | "), " |")
  }
  emit("")
}

emit("# Exploratory analysis")
emit("")
emit("Generated by `R/03_eda.R` — regenerate with `make eda`. ",
     "Seed 20260823, ", BOOT_REPS, " bootstrap replicates.")
emit("")

# ------------------------------------------------------------ cohort table

deaths     <- sum(df$event)
followup   <- summary(df$time_months)
emit("## Cohort")
emit("")
cohort_tbl <- data.frame(
  Measure = c("Participants", "Deaths", "Crude mortality", "Person-months",
              "Median follow-up (months)", "Follow-up range (months)",
              "Labelled for the 36-month endpoint", "Deaths within 36 months"),
  Value = c(
    format(nrow(df), big.mark = ","),
    format(deaths, big.mark = ","),
    sprintf("%.2f%%", 100 * deaths / nrow(df)),
    format(sum(df$time_months), big.mark = ","),
    sprintf("%.0f", followup[["Median"]]),
    sprintf("%d–%d", min(df$time_months), max(df$time_months)),
    format(sum(!is.na(df$event_36)), big.mark = ","),
    format(sum(df$event_36 == 1, na.rm = TRUE), big.mark = ",")
  )
)
md_table(cohort_tbl)

# ------------------------------------------------- categorical vs mortality

emit("## Categorical predictors versus mortality")
emit("")
emit("Pearson chi-square on the predictor × death contingency table. ",
     "`unknown` rows are excluded from each test and counted separately.")
emit("")

chi_rows <- list()
for (v in CATEGORICAL) {
  sub <- df[df[[v]] != "unknown", ]
  tab <- table(sub[[v]], sub$event)
  if (nrow(tab) < 2) next
  test <- suppressWarnings(chisq.test(tab))
  rates <- 100 * tab[, "1"] / rowSums(tab)
  worst <- names(which.max(rates))
  best  <- names(which.min(rates))
  chi_rows[[v]] <- data.frame(
    Predictor = v,
    n = format(nrow(sub), big.mark = ","),
    Unknown = sum(df[[v]] == "unknown"),
    `Chi-square` = sprintf("%.1f", test$statistic),
    df = test$parameter,
    `Highest mortality` = sprintf("%s (%.1f%%)", worst, max(rates)),
    `Lowest mortality`  = sprintf("%s (%.1f%%)", best,  min(rates)),
    p_raw = test$p.value,
    check.names = FALSE
  )
}
chi_df <- do.call(rbind, chi_rows)

# --------------------------------------------------- continuous vs mortality

t_rows <- list()
for (v in CONTINUOUS) {
  alive <- df[[v]][df$event == 0]
  dead  <- df[[v]][df$event == 1]
  alive <- alive[!is.na(alive)]
  dead  <- dead[!is.na(dead)]
  test  <- t.test(dead, alive, var.equal = FALSE)
  t_rows[[v]] <- data.frame(
    Predictor = v,
    `Mean (survived)` = sprintf("%.2f", mean(alive)),
    `Mean (died)`     = sprintf("%.2f", mean(dead)),
    Difference = sprintf("%+.2f", test$estimate[1] - test$estimate[2]),
    `95% CI` = sprintf("[%+.2f, %+.2f]", test$conf.int[1], test$conf.int[2]),
    p_raw = test$p.value,
    check.names = FALSE
  )
}
t_df <- do.call(rbind, t_rows)

# Holm across every test run against the outcome in this file.
all_p <- c(chi_df$p_raw, t_df$p_raw)
adjusted <- p.adjust(all_p, method = "holm")
chi_df$`p (Holm)` <- fmt_p(adjusted[seq_len(nrow(chi_df))])
t_df$`p (Holm)`   <- fmt_p(adjusted[(nrow(chi_df) + 1):length(adjusted)])
chi_df$p_raw <- NULL
t_df$p_raw   <- NULL

md_table(chi_df)

emit("> **The smoking result is confounded by age.** Former smokers show higher ",
     "crude mortality than current smokers, which inverts the expected ordering. ",
     "People quit smoking as they age and as they become ill, so the `former` ",
     "group is substantially older. Mean age by group:")
emit("")
age_by_smoker <- aggregate(age ~ smoker, data = df, FUN = mean)
age_by_smoker$age <- sprintf("%.1f", age_by_smoker$age)
names(age_by_smoker) <- c("Smoking status", "Mean age")
md_table(age_by_smoker)
emit("Adjusted models in `R/04_models.R` are what settle this; the crude table ",
     "above should not be read as a causal effect of quitting.")
emit("")

emit("## Continuous predictors versus mortality")
emit("")
emit("Welch two-sample t-test (unequal variances), died minus survived. ",
     "Complete cases per predictor.")
emit("")
md_table(t_df)

# --------------------------------------------------------------- bootstrap

emit("## Bootstrap confidence intervals")
emit("")
emit("Percentile bootstrap, ", format(BOOT_REPS, big.mark = ","),
     " replicates, on the difference in means between those who died and those ",
     "who survived. The t-test above assumes approximate normality of the ",
     "sampling distribution; this makes no such assumption.")
emit("")

mean_diff <- function(data, indices) {
  d <- data[indices, ]
  mean(d$value[d$event == 1], na.rm = TRUE) - mean(d$value[d$event == 0], na.rm = TRUE)
}

boot_rows <- list()
for (v in c("age", "bmi", "sbp", "hba1c")) {
  d <- data.frame(value = df[[v]], event = df$event)
  d <- d[!is.na(d$value), ]
  b <- boot(d, mean_diff, R = BOOT_REPS)
  ci <- boot.ci(b, type = "perc")
  boot_rows[[v]] <- data.frame(
    Predictor = v,
    `Observed difference` = sprintf("%+.2f", b$t0),
    `Bootstrap SE` = sprintf("%.3f", sd(b$t)),
    `95% CI (percentile)` = sprintf("[%+.2f, %+.2f]", ci$percent[4], ci$percent[5]),
    `Excludes zero` = ifelse(ci$percent[4] > 0 | ci$percent[5] < 0, "yes", "no"),
    check.names = FALSE
  )
}
md_table(do.call(rbind, boot_rows))

# ------------------------------------------------------ survival / log-rank

emit("## Survival curves and log-rank tests")
emit("")

km_plot <- function(formula, data, title, filename, legend_title) {
  fit <- survfit(formula, data = data)
  png(file.path(FIGS_DIR, filename), width = 900, height = 620, res = 130)
  on.exit(dev.off(), add = TRUE)
  par(mar = c(4.5, 4.5, 3, 1))
  plot(fit, col = seq_along(fit$strata), lty = 1, lwd = 2,
       xlab = "Months since examination", ylab = "Survival probability",
       main = title, ylim = c(0.80, 1))
  legend("bottomleft", bty = "n", lwd = 2,
         col = seq_along(fit$strata),
         title = legend_title,
         legend = sub(".*=", "", names(fit$strata)))
  invisible(fit)
}

logrank_rows <- list()
for (spec in list(
  list(var = "smoker",   keep = c("never", "former", "current"),
       file = "km_smoking.png",  label = "Smoking status"),
  list(var = "diabetes", keep = c("no", "borderline", "yes"),
       file = "km_diabetes.png", label = "Diabetes")
)) {
  sub <- df[df[[spec$var]] %in% spec$keep, ]
  f <- as.formula(sprintf("Surv(time_months, event) ~ %s", spec$var))
  km_plot(f, sub, paste("Kaplan-Meier survival by", tolower(spec$label)),
          spec$file, spec$label)
  sd_test <- survdiff(f, data = sub)
  pval <- pchisq(sd_test$chisq, df = length(sd_test$n) - 1, lower.tail = FALSE)
  logrank_rows[[spec$var]] <- data.frame(
    Stratification = spec$label,
    Groups = length(sd_test$n),
    n = format(sum(sd_test$n), big.mark = ","),
    `Observed deaths` = sum(sd_test$obs),
    `Log-rank chi-square` = sprintf("%.1f", sd_test$chisq),
    p = fmt_p(pval),
    Figure = sprintf("![](figs/%s)", spec$file),
    check.names = FALSE
  )
}
md_table(do.call(rbind, logrank_rows))

emit("![Kaplan-Meier by smoking status](figs/km_smoking.png)")
emit("")
emit("![Kaplan-Meier by diabetes status](figs/km_diabetes.png)")
emit("")

emit("## Caveats")
emit("")
emit("- **Survey weights are not applied.** NHANES uses a complex multistage ",
     "design; every figure here describes this sample, not the U.S. population.")
emit("- **Crude comparisons only.** Nothing above adjusts for age or any other ",
     "covariate. See the smoking note.")
emit("- **Follow-up ends in 2019**, a median of ",
     sprintf("%.0f", followup[["Median"]]),
     " months after examination, which is why the binary endpoint is 36 months ",
     "rather than 60.")

close(con_md)

cat("Wrote", OUT_MD, "and", length(list.files(FIGS_DIR, pattern = "[.]png$")),
    "figures\n")
